env_id: 'girdCL-v0'
method: 'random'
config_path: 'min_red/config'
algorithm_type: PPO  # SoftQ, PPO
total_timesteps: 100000
env_kwargs:
  n_actions: 4
  max_steps: 100
  simplify_action: False
  image_output: False
vec_env_kwargs: 'empty_dict'
is_atari: False
play_model: False
save_model: True
wandb: False
