env_id: 'empty_dict'
config_path: 'pureppo/config'
algorithm_type: PPO  # SoftQ, PPO
total_timesteps: 100000
env_kwargs: 'empty_dict'
vec_env_kwargs: 'empty_dict'
is_atari: False
play_model: False
save_model: True
