env_id: 'memoryar-v0'
config_path: 'puredqn/config'
algorithm_type: DQN  # SoftQ, PPO
total_timesteps: 100000
env_kwargs: 'empty_dict'
vec_env_kwargs: 'empty_dict'
is_atari: False
play_model: True
save_model: True
