env_id: 'rooms-v0'
#method: 'stochastic'
config_path: 'pureppo/config'
algorithm_type: PPO  # SoftQ, PPO
total_timesteps: 100000
env_kwargs:
  rows: 16
  cols: 16
  empty: False
  goal: [1, 1]
  state: [14, 14]
  fixed_reset: True
  vert_wind: [0.2, 0.0] # (up, down)
  horz_wind: [0.0, 0.0] # (right, left)
  n_redundancies: 35
  max_repeats: 3
  vis: False
vec_env_kwargs: 'empty_dict'
is_atari: False
play_model: True
save_model: True
wandb: False
